FROM postgres:17.2-alpine

ENV POSTGRES_DB=db \
   POSTGRES_USER=usr \
   POSTGRES_PASSWORD=pwd


   # Pour créér l'image : docker build -t eucko/dbtp1
   # Pour créér et lancer le conteneur : docker run -p
